#!/bin/sh
set -e

case "$1" in
    configure|abort-upgrade)
	[ -x /usr/share/update-notifier/notify-reboot-required ] && /usr/share/update-notifier/notify-reboot-required || true
	;;

    triggered)
	[ -x /usr/bin/lastore-tools ] && /usr/bin/lastore-tools -item desktop -output /var/lib/lastore/ || true

	# old store.api, used to marking opened desktop file
	[ -x /var/lib/lastore/mark-desktopfile-daemon ] && /var/lib/lastore/mark-desktopfile-daemon -s || true
	;;
esac
