#!/bin/sh

set -e

USER=deepin-daemon

if [ "$1" = configure ];then
    adduser --system \
        --quiet \
        --no-create-home \
        --disabled-password \
        --group "$USER"

    if [ -f /etc/systemd/logind.conf ];then
        sed -i 's/^#\?HandlePowerKey=.*$/HandlePowerKey=ignore/g' /etc/systemd/logind.conf || true
        sed -i 's/^#\?HandleLidSwitch=.*$/HandleLidSwitch=ignore/g' /etc/systemd/logind.conf || true
    fi

fi
if [ -f /usr/share/fcitx/addon/fcitx-xkb.conf ];then
    sed -i 's/Enabled=.*$/Enabled=False/' /usr/share/fcitx/addon/fcitx-xkb.conf || true
fi
if [ "$1" = "triggered" ];then
    /usr/lib/deepin-daemon/theme-thumb-tool -o /var/cache/thumbnails/appearance/ all
fi
#DEBHELPER#
