#!/bin/sh

set -e

if [ "$1" = configure ];then
    if [ -f /etc/systemd/logind.conf ];then
        sed -i 's/^#\?HandlePowerKey=.*$/HandlePowerKey=ignore/g' /etc/systemd/logind.conf || true
        sed -i 's/^#\?HandleLidSwitch=.*$/HandleLidSwitch=ignore/g' /etc/systemd/logind.conf || true
    fi

fi
if [ -f /usr/share/fcitx/addon/fcitx-xkb.conf ];then
    sed -i 's/Enabled=.*$/Enabled=False/' /usr/share/fcitx/addon/fcitx-xkb.conf || true
fi
#DEBHELPER#
