#!/bin/sh

set -e

case "$1" in
    configure)
        #append line to /etc/pam.d/login
        login_hits="session    optional   pam_exec.so type=open_session stdout /usr/bin/deepin-activator-cli -s"
        echo $login_hits >> /etc/pam.d/login
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac
#DEBHELPER#
exit 0
